"""empty message

Revision ID: b7440b08a2e9
Revises: 
Create Date: 2024-09-27 16:17:04.614726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7440b08a2e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('faces_counter', sa.Integer(), nullable=False),
    sa.Column('women_counter', sa.Integer(), nullable=False),
    sa.Column('male_counter', sa.Integer(), nullable=False),
    sa.Column('men_avg_age', sa.Float(), nullable=False),
    sa.Column('women_avg_age', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('unique_filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_filename')
    )
    op.create_table('faces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('gender', sa.String(length=500), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('age', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faces')
    op.drop_table('images')
    op.drop_table('tasks')
    # ### end Alembic commands ###
